#!/usr/bin/env bash
set -euo pipefail

# setup.sh — Bootstrap the knowledge-os-mcp development environment.
#
# What this script does:
#   1. Checks Python 3.11+ is available
#   2. Creates a Python virtualenv at .venv
#   3. Installs all requirements from requirements.txt
#   4. Checks cloudflared is on PATH (or provides install instructions)
#   5. Emits ~/.cloudflared/config.yml template (if it doesn't already exist)
#   6. Prints final manual steps the user must complete
#
# What this script does NOT do:
#   - It does NOT create a Cloudflare Tunnel (requires interactive login)
#   - It does NOT run cloudflared login (requires browser auth)
#   - It does NOT populate .env (secrets must be set manually)
#   - It does NOT run init_vault.py (VAULT_PATH must be set first)

echo "==> knowledge-os-mcp setup"
echo ""

# ---------------------------------------------------------------------------
# Step 1: Check Python 3.11+
# ---------------------------------------------------------------------------
echo "--- Checking Python version ---"

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 not found. Install Python 3.11+ via:"
    echo "  brew install python@3.11"
    exit 1
fi

PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PYTHON_MAJOR=$(python3 -c "import sys; print(sys.version_info.major)")
PYTHON_MINOR=$(python3 -c "import sys; print(sys.version_info.minor)")

if [ "$PYTHON_MAJOR" -lt 3 ] || { [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 11 ]; }; then
    echo "ERROR: Python 3.11+ required. Found Python $PYTHON_VERSION."
    echo "  Install via: brew install python@3.11"
    exit 1
fi

echo "  OK — Python $PYTHON_VERSION"

# ---------------------------------------------------------------------------
# Step 2: Create virtualenv at .venv
# ---------------------------------------------------------------------------
echo ""
echo "--- Creating Python virtualenv at .venv ---"

if [ -d ".venv" ]; then
    echo "  .venv already exists — skipping creation"
else
    python3 -m venv .venv
    echo "  OK — virtualenv created at .venv/"
fi

# ---------------------------------------------------------------------------
# Step 3: Activate venv and install requirements
# ---------------------------------------------------------------------------
echo ""
echo "--- Installing Python dependencies ---"

# shellcheck disable=SC1091
source .venv/bin/activate

pip install --upgrade pip --quiet
pip install -r requirements.txt

echo "  OK — all packages installed"

# ---------------------------------------------------------------------------
# Step 4: Check cloudflared
# ---------------------------------------------------------------------------
echo ""
echo "--- Checking cloudflared ---"

if ! command -v cloudflared &>/dev/null; then
    echo "WARNING: cloudflared not found on PATH."
    echo "  Install via: brew install cloudflared"
    echo "  Then run this script again, or complete the Cloudflare Tunnel setup manually."
    echo "  (Continuing setup — you can install cloudflared later)"
    CLOUDFLARED_FOUND=false
else
    CLOUDFLARED_VERSION=$(cloudflared version 2>&1 | head -1)
    echo "  OK — $CLOUDFLARED_VERSION"
    CLOUDFLARED_FOUND=true
fi

# ---------------------------------------------------------------------------
# Step 5: Emit ~/.cloudflared/config.yml template (if cloudflared found)
# ---------------------------------------------------------------------------
if [ "$CLOUDFLARED_FOUND" = true ]; then
    echo ""
    echo "--- Checking Cloudflare Tunnel config ---"

    CLOUDFLARED_CONFIG="$HOME/.cloudflared/config.yml"

    if [ -f "$CLOUDFLARED_CONFIG" ]; then
        echo "  ~/.cloudflared/config.yml already exists — skipping template generation"
    else
        mkdir -p "$HOME/.cloudflared"
        cat > "$CLOUDFLARED_CONFIG" << 'CFEOF'
# ~/.cloudflared/config.yml
# Generated by knowledge-os-mcp setup.sh
# Replace all <PLACEHOLDER> values with your actual tunnel details.
#
# To get your TUNNEL-UUID:
#   cloudflared tunnel login
#   cloudflared tunnel create vault
#   (The UUID is printed after tunnel creation)

tunnel: <TUNNEL-UUID>
credentials-file: /Users/<YOUR-USERNAME>/.cloudflared/<TUNNEL-UUID>.json

ingress:
  - hostname: vault.<your-domain.com>
    service: http://localhost:8000
  - service: http_status:404
CFEOF
        echo "  OK — template written to ~/.cloudflared/config.yml"
        echo "  Edit it to replace <TUNNEL-UUID>, <YOUR-USERNAME>, and <your-domain.com>"
    fi
fi

# ---------------------------------------------------------------------------
# Step 6: Final instructions
# ---------------------------------------------------------------------------
echo ""
echo "============================================================"
echo "  Setup complete — manual steps remaining:"
echo "============================================================"
echo ""
echo "  1. Set up Cloudflare Tunnel (if not done):"
echo "       cloudflared tunnel login"
echo "       cloudflared tunnel create vault"
echo "       cloudflared tunnel route dns vault vault.<your-domain.com>"
echo "     Then edit ~/.cloudflared/config.yml with your tunnel UUID and domain."
echo ""
echo "  2. Populate .env:"
echo "       cp .env.example .env"
echo "       # Edit .env and set:"
echo "       #   VAULT_SECRET=<random-secret>   (use: openssl rand -hex 32)"
echo "       #   VAULT_PATH=<absolute-path-to-new-vault-dir>"
echo "       #   OAUTH_CLIENT_ID=<your-client-id>"
echo "       #   OAUTH_REDIRECT_URI=<your-redirect-uri>"
echo ""
echo "  3. Initialize the vault:"
echo "       source .env"
echo "       python init_vault.py"
echo ""
echo "  4. Start the server with PM2:"
echo "       npm install -g pm2   # if not already installed"
echo "       pm2 start ecosystem.config.js"
echo "       pm2 save"
echo "       pm2 startup          # auto-start on boot"
echo ""
echo "  5. Configure MCP client:"
echo "     - Claude Desktop (local): point to http://localhost:8000/mcp"
echo "     - claude.ai mobile (remote): use OAuth connector at https://vault.<your-domain.com>"
echo ""
